config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "posts#index"
  get '/new_post' => 'posts#new'
  post '/new_post' => 'posts#create'
  resources :users 
  resources :posts do 
    resources :comments, :except => [:show, :index]
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :text, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, :presence => true
  validates :text, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user])
  end

  def logged_in?
    current_user != nil
  end
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment Added"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:alert] = "Comment deleted"
    redirect_to post_path(@post)
  end




  private
  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post added!"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post])
      flash[:notice] = "Post updated"
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:alert] = "Post deleted"
    redirect_to posts_path
  end 




  private

  def post_params
    params.require(:post).permit(:title, :text, :timestamp, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:index]

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<%= bootstrap_form_for [@post, @comment] do |f| %>
  <%= f.text_field :text %>
  <p><%= f.submit "Update Comment" %><p/>
<% end %>

app/views/comments/new.html.erb
<h1>New comment for <%= @post.title %></h1>

<%= bootstrap_form_for [@post, @comment] do |f| %>
  <%= f.text_field :text %>
  <p><%= f.submit "Add comment" %><p/>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li><%= link_to 'Blog', posts_path %></li>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Join us", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloggin'</title>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif|Titillium+Web' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= yield %>


  </div>

</body>
</html>

app/views/posts/edit.html.erb
<%= render 'shared/header' %>

<%= bootstrap_form_for(@post) do |f| %>
  <%=f.text_field :title %>
  <%=f.text_area :text %>
  <%=f.submit "Edit Post" %>
<% end %>

app/views/posts/index.html.erb
<%= render 'layouts/flash' %>

<h1>Posts</h1>
<div class="post">
<% @posts.each do |post| %>
  <ul>
    <p><%= link_to post.title, post_path(post)%></p>
    <p><%= post.created_at.strftime("%B %d, %Y")  %></p>
  </ul>
<% end %>
</div>

<div class="btn-group">
  <%= link_to "New Post", new_post_path, :class => "btn btn-primary" %>
</div>

app/views/posts/new.html.erb
<%= render 'layouts/flash' %>

<%= bootstrap_form_for(@post) do |f| %>
  <%=f.text_field :title %>
  <%=f.text_area :text %>
  <%=f.submit "Add post" %>
<% end %>

app/views/posts/show.html.erb
<%= render 'layouts/flash' %>

<h2><%= @post.title %></h2>
<h4><%= "Posted on " + @post.created_at.strftime("%B %d, %Y") %></h4>

<p><%= @post.text %></p>

<div class="btn-group">
  <%= link_to "Add a comment", new_post_comment_path(@post), :class => "btn btn-primary" %>
</div>

<div class="btn-group">
  <%= link_to "Edit Post", edit_post_path, :class => "btn btn-primary" %>
</div>

<div class="btn-group">
  <%= link_to "Delete Post", post_path(@post), :class => "btn btn-primary",
                                      :data => {:confirm => "Do you really want this?",
                                      :method => "delete"} %>
  </div>

<% if @post.comments.any? %>
  <h4>Comments:</h4>
  <ul>
    <% @post.comments.each do |comment| %>
    <li>
      <%= comment.text %>
      <%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %> |
      <%= link_to "Delete Comment", post_comment_path(@post, comment),
                                      :data => {:confirm => "For reals?",
                                      :method => "delete"} %> 
    </li>  
    <% end %>
    </ul>
<% end %>


<div class="btn-group">
  <%= link_to "Back", posts_path, :class => "btn btn-primary" %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %> 